name: CI
on:
  create: # when tags are created
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore src/ImGui.NET
        dotnet restore src/ImPlot.NET
        dotnet restore src/ImNodes.NET
        dotnet restore src/ImGuizmo.NET
        dotnet restore src/CodeGenerator

    - name: Build Project
      run: |
        dotnet build -c Release --no-restore src/ImGui.NET
        dotnet build -c Release --no-restore src/ImPlot.NET
        dotnet build -c Release --no-restore src/ImNodes.NET
        dotnet build -c Release --no-restore src/ImGuizmo.NET
        dotnet build -c Release --no-restore src/CodeGenerator

    - name: Build Packages
      if: matrix.os == 'windows-latest'
      run: dotnet pack src/ImGui.NET -c Release --no-restore --no-build

    - name: List Packages
      if: matrix.os == 'windows-latest'
      run: ls -l bin\Release\ImGui.NET\
